name: CI

on: [pull_request, workflow_dispatch]

jobs:
  ci:
    runs-on: ubuntu-latest
    timeout-minutes: 35
    steps:
      - uses: actions/checkout@v2

      - name: set up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '11'

      - name: Copy CI gradle.properties
        run: mkdir -p ~/.gradle ; cp .github/ci-gradle.properties ~/.gradle/gradle.properties

      - name: Switch to Gradle Binary Distribution
        run: sed -i -e 's/-all.zip/-bin.zip/' gradle/wrapper/gradle-wrapper.properties

      - name: Prefetch Robolectric jars
        run: |
          mkdir robolectric-jars
          wget -P robolectric-jars https://repo1.maven.org/maven2/org/robolectric/android-all/7.1.0_r7-robolectric-r1/android-all-7.1.0_r7-robolectric-r1.jar
          wget -P robolectric-jars https://repo1.maven.org/maven2/org/robolectric/android-all/9-robolectric-4913185-2/android-all-9-robolectric-4913185-2.jar
          wget -P robolectric-jars https://repo1.maven.org/maven2/org/robolectric/android-all/10-robolectric-5803371/android-all-10-robolectric-5803371.jar

      - name: Build and Test SDK
        run: bash ./gradlew build --info --stacktrace

      - name: publish unit test reports
        if: always()
        uses: mikepenz/action-junit-report@a6502270b81b22b7cf745720fcf00edf7d31dc04
        with:
          check_name: 'Unit test reports'
          github_token: ${{ github.token }}
          report_paths: '**/build/test-results/**/TEST-*.xml'
          fail_on_failure: true
