name: Release

on:
  push:
    tags:
      - "[0-9]+.[0-9]+.[0-9]+*"

jobs:
  release:
    if: github.repository == 'urbanairship/android-library'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Get the version
        id: get_version
        run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}

      - name: Get the release notes
        id: get_release_notes
        run: |
          VERSION=${{ steps.get_version.outputs.VERSION }}
          NOTES="$(awk "/## Version $VERSION/{flag=1;next}/## Version/{flag=0}flag" CHANGELOG.md)"
          NOTES="${NOTES//'%'/'%25'}"
          NOTES="${NOTES//$'\n'/'%0A'}"
          NOTES="${NOTES//$'\r'/'%0D'}"
          echo ::set-output name=NOTES::"$NOTES"

      - name: Verify Version
        run: |
          VERSION=${{ steps.get_version.outputs.VERSION }}
          if [[ $(./gradlew -q getVersion) = $VERSION ]]; then exit 0 ; else exit 1; fi

      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Setup GCP
        uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
        with:
          version: "270.0.0"
          service_account_email: ${{ secrets.GCP_SA_EMAIL }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}

      - name: Build
        run: ./gradlew build packageDocs

      - name: Upload docs
        run: |
          VERSION=${{ steps.get_version.outputs.VERSION }}
          gsutil cp build/docs/$VERSION.tar.gz gs://ua-web-ci-prod-docs-transfer/libraries/android/$VERSION.tar.gz

      - name: Github Release
        uses: actions/create-release@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.get_version.outputs.VERSION }}
          release_name: ${{ steps.get_version.outputs.VERSION }}
          body: ${{ steps.get_release_notes.outputs.NOTES }}
          draft: false
          prerelease: false

      - name: Upload bintray
        env:
          BINTRAY_USER: ${{ secrets.BINTRAY_USER }}
          BINTRAY_API_KEY: ${{ secrets.BINTRAY_API_KEY }}
          MAVEN_USER: ${{ secrets.MAVEN_USER }}
          MAVEN_PASSWORD: ${{ secrets.MAVEN_PASSWORD }}
        run: |
          ./gradlew urbanairship-core:bintrayUpload --stacktrace
          ./gradlew urbanairship-automation:bintrayUpload --stacktrace
          ./gradlew urbanairship-message-center:bintrayUpload --stacktrace
          ./gradlew urbanairship-location:bintrayUpload --stacktrace
          ./gradlew urbanairship-ads-identifier:bintrayUpload --stacktrace
          ./gradlew urbanairship-preference:bintrayUpload --stacktrace
          ./gradlew urbanairship-accengage:bintrayUpload --stacktrace
          ./gradlew urbanairship-fcm:bintrayUpload --stacktrace
          ./gradlew urbanairship-adm:bintrayUpload --stacktrace
          ./gradlew urbanairship-hms:bintrayUpload --stacktrace
          ./gradlew urbanairship-chat:bintrayUpload --stacktrace

      - name: Sync to maven central
        env:
          BINTRAY_USER: ${{ secrets.BINTRAY_USER }}
          BINTRAY_API_KEY: ${{ secrets.BINTRAY_API_KEY }}
          MAVEN_USER: ${{ secrets.MAVEN_USER }}
          MAVEN_PASSWORD: ${{ secrets.MAVEN_PASSWORD }}
        run: |
          ./gradlew urbanairship-core:syncToMavenCentral --stacktrace
          ./gradlew urbanairship-automation:syncToMavenCentral --stacktrace
          ./gradlew urbanairship-message-center:syncToMavenCentral --stacktrace
          ./gradlew urbanairship-location:syncToMavenCentral --stacktrace
          ./gradlew urbanairship-ads-identifier:syncToMavenCentral --stacktrace
          ./gradlew urbanairship-preference:syncToMavenCentral --stacktrace
          ./gradlew urbanairship-accengage:syncToMavenCentral --stacktrace
          ./gradlew urbanairship-fcm:syncToMavenCentral --stacktrace
          ./gradlew urbanairship-adm:syncToMavenCentral --stacktrace
          ./gradlew urbanairship-hms:syncToMavenCentral --stacktrace
          ./gradlew urbanairship-chat:syncToMavenCentral --stacktrace
